@extends('layouts.app')
<div class="termeni-text-box">
<h2 class="text-center term-gap" >Termeni si conditii de utilizare a platformei</h1>
<h4 class="gap-par">1. Acceptarea Termenilor și Condițiilor</h4>
<p>Acești termeni și condiții (“<b>Termeni și Condiții</b>”) constituie acordul legal dintre dvs. și Angrro. Vă rugăm să citiți acești Termeni și Condiții pentru utilizarea în orice mod a website-ului accesibil la adresa URL: www.angrro.ro (“Website-ul”). Accesarea și vizitarea Website-ului, înregistrarea unui cont pe Website și/sau folosirea serviciilor de publicare pe Website de anunțuri pentru vânzarea, cumpărarea sau închirierea de bunuri sau servicii (“Serviciile”) înseamnă acceptarea în totalitate și necondiționată a acestor <b>Termeni și Condiții.</b></p>
<h4 class="gap-par" >2. Definiții</h1>
<p>Termenii folosiți în continuare vor avea următorul înțeles:</p>
<p><b>Utilizator</b> - orice persoană fizică, în vârstă de cel puțin 18 ani, cu capacitate de exercițiu deplină, care accesează Website-ul, fiind interesată de datele, informațiile, Anunțurile și/sau Serviciile Angrro Online Services S.R.L., precum și orice persoană fizică (inclusiv persoană fizică autorizată) și/sau persoană juridică care achiziționează Serviciile furnizate prin intermediul Website-ului.</p>
<p><b>Anunț</b> - oferta publică lansată de un Utilizator cu scopul de a fi publicată de către Angrro prin intermediul Website-ului, cu privire la vânzarea sau închirierea unui Produs.</p>
<p><b>Produs</b> – bun sau serviciu care poate fi comercializat conform legii și care nu încalcă limitele impuse prin acești Termeni și Condiții.</p>
<p><b>Pagina Angrro</b> - site-ul www.Angrro.ro, inclusiv orice secțiune sau subpagină a acestuia. Site-urile și/sau paginile de internet ori alte componente ale acestora ce aparțin unor terți și care sunt accesate de către Utilizatori ca urmare a legăturilor sau trimiterilor disponibile pe site-ul www.angrro.ro nu fac obiectul și nici nu intră în sfera acestei definiții.</p>
<p><b>Anunț gratuit</b> - anunț care poate fi publicat de Utilizatori pe Pagina Angrro fără perceperea unei taxe de către Furnizor.</p>
<p><b>Limită Anunțuri Gratuite</b> - Limita Anunțurilor Gratuite se consideră a fi atinsă în momentul în care Utilizatorul folosește ultimul Anunț Gratuit disponibil în oferta Furnizorului aferentă unei categorii.</p>
<p><b>Operatori</b> - persoane special instruite de către Furnizor pentru verificarea/moderarea conținutului Anunțurilor publicate de către Utilizatori pe Website.</p>
<p><b>Sistem de evaluare</b> (rating și feedback) - sistem de rating și feedback, care permite Utilizatorului să ofere celorlalți Utilizatori o evaluare subiectivă asupra experienței tranzacționale. Experiența tranzacțională se evaluează, în mod special, în funcție de: existența unei descrieri clare și serioase a Produsului, modul de comunicare între Utilizatori, receptivitate, implicare, timpul de achiziționare si/sau livrare a Produsului, punctualitate, etc. Baza evaluării este contactul dintre Utilizatori, sub orice formă, și nu exclusiv încheierea efectivă unei tranzacții.</p>
<p>Prin acordul dvs. referitor la acești Termeni și Condiții, dvs. declarați și garantați că aveți 18 ani și capacitate deplină de exercițiu sau, în cazul unei persoane juridice, sunteți o societate înmatriculată și funcționând în conformitate cu legile din România, iar reprezentanții dvs. sunt în mod valabil autorizați să exprime acordul dvs. legal cu privire la accesarea, vizitarea sau utilizarea, în orice alt mod, a Website-ul si/sau a Serviciilor.</p>
<p>Angrro își rezervă dreptul de a modifica sau de a actualiza oricând unilateral Termenii și Condițiile. Puteți accesa Termenii și Condițiile oricând la adresa: Angrro.ro/termeni-de-utilizare.</p>
<p>Dacă nu ștergeți contul înregistrat pe Website, înseamnă ca v-ați exprimat acordul legal cu privire la modificarea Termenilor și Condițiilor. Dacă nu sunteți de acord cu modificările propuse, singura opțiune pe care o aveți este să ștergeți contul înregistrat pe Website sau să nu mai accesați, să vizitați sau să utilizați, în orice mod, Website-ul.</p>
<h4 class="gap-par" >3. Asepcte Generale</h4>
<p>Un Anunț va fi creat prin completarea unui formular, disponibil pe Website, care să conțină:</p>
<ul>
  <li>datele reale de contact ale Utilizatorului;</li>
  <li>descrierea reală a Produsului care face obiectul Anunțului; și</li>
  <li>prețul Produsului care face obiectul Anunțului.</li>
</ul>
<p>Prin trimiterea Anunțului spre publicare către Furnizor, Utilizatorul declară că este de acord în totalitate și necondiționat cu prevederile acestor Termeni și Condiții, fiind pe deplin de acord ca, în caz de nerespectare a acestora, să fie tras la răspundere conform prevederilor acestora. Utilizatorul își asumă în întregime răspunderea pentru conținutul Anunțului și pentru veridicitatea informațiilor publicate în Anunț și/sau comunicate Furnizorului.</p>
<p>Procedura de afișare a unui Anunț pe Website este detaliată la secțiunea intitulată „Ajutor” de pe Website.</p>
<p>Valabilitatea unui Anunț pe site este de 30 de zile, cu posibilitatea de prelungire la sfârșitul acestui termen. Detalii practice despre cum puteți prelungi Anunțul la expirarea acestuia regăsiți aici.</p>
<h4 class="gap-par" >4.Drepturile și Obligațiile Furnizorului</h4>
<p>Furnizorul se obligă să publice toate Anunțurile transmise de către Utilizatori prin intermediul Website-ului care sunt conforme cu prevederile/condițiile impuse prin prezentul document.</p>
<p>Furnizorul se obligă să remedieze în cel mai scurt timp posibil eventualele disfuncționalități reclamate, legate de funcționarea Website-ului sau eventuale neconcordanțe între datele furnizate în Anunț de către Utilizator și datele publicate pe Website de către Furnizor, cu excepția acelor neconcordanțe care se datorează faptului că Operatorii Furnizorului au modificat parțial Anunțul, astfel încât acesta să îndeplinească condițiile impuse prin prezentul document, pentru a putea fi menținut postat pe Website.</p>
<p>Furnizorul nu oferă nicio garanție Utilizatorilor că Website-ul va fi disponibil neîntrerupt, la timp, sigur sau fără erori. Furnizorul nu va fi responsabil pentru neafișarea Anunțurilor sau întreruperea afișării acestora din cauze ce exced, în orice mod, controlului său și nici pentru pagubele directe și/sau indirecte pe care Utilizatorul le-ar putea suferi din această cauză.</p>
<p>Furnizorul nu este responsabil de întârzierile cauzate de defecțiuni tehnice apărute la nivelul colaboratorilor și/sau partenerilor săi.</p>
<p>Furnizorul nu poate fi tras la răspundere pentru activitățile Utilizatorilor, în special pentru furnizarea de conținut eronat cu privire la datele Produsului sau serviciului ce face obiectul Anunțului.</p>
<p>Furnizorul își rezervă dreptul de a șterge sau modifica parțial un Anunț, în cazul în care se constată că acesta încalcă Termenii și Condițiile, în orice mod, în special în cazul în care acesta are un conținut considerat jignitor sau calomnios, constituie concurență neloială, încalcă drepturile de proprietate intelectuală ale unei terțe persoane sau este contrar bunelor practici, care acționează în detrimentul Furnizorului, ori încalcă, în orice alt mod, vreo prevedere legală. De asemenea, Furnizorul își rezervă dreptul de a suspenda, modifica, adăuga sau șterge, în orice moment, și alte porțiuni din conținutul Website-ului.</p>
<p>Furnizorul are dreptul de a șterge orice Anunț sau de a bloca conturile în cazul în care există suspiciunea că, prin intermediul Anunțurilor publicate sau a conturilor create, s-au adus sau se pot aduce prejudicii referitoare la securitatea activității altor Utilizatori ai serviciului. De asemenea, Furnizorul are dreptul de a șterge Anunțul sau de a bloca contul, în cazul în care Anunțul afectează în mod negativ reputația Furnizorului sau este, în orice alt fel, dăunător pentru Furnizor.</p>
<p>Furnizorul declară că este titularul tuturor drepturilor de proprietate intelectuală în legătură cu Website-ul, în afara Anunțurilor publicate pe Website de către Utilizatori, cu privire la care Utilizatorii acordă Furnizorului un drept neexclusiv de utilizare și punere la dispoziția publicului, în condițiile prevăzute în acest document.</p>
<p>Furnizorul nu își asumă niciun fel de răspundere pentru conținutul sau veridicitatea Anunțurilor publicate. Furnizorul nu garantează în niciun fel și nicio măsura pentru calitatea, cantitatea, disponibilitatea sau orice alte aspecte ale Produselor descrise în Anunțuri.</p>
<p>Potrivit legislației în vigoare, Furnizorul are obligația să informeze de îndată autoritățile publice competente despre activitățile cu aparență nelegală, desfășurate de destinatarii serviciilor sale sau despre informațiile cu aparență nelegală furnizate de Utilizatorii Website-ului.</p>
<p>Angrro va putea efectua teste și analize statistice în vederea optimizării și eficientizării politicilor practicate și în scopul îmbunătățirii, în mod obiectiv și nedescriminatoriu, a activității Angrro și a experienței Utilizatorilor, fără ca Angrro să aibă obligația de a informa Utilizatorii cu privire la efectuarea testelor sau la rezultatele acestora. Orice Utilizator care nu dorește să facă parte din grupul de Utilizatori care, în mod aleatoriu, ajung să participe în aceste teste sau orice alt Utilizator care consideră că este dezavantajat de o astfel de inițiativă, are dreptul să solicite lămuriri privind statutul său, urmând ca Angrro să depună toate diligențele necesare pentru a concilia situația sesizată, atât timp cât solicitarea Utilizatorului se dovedește a fi una întemeiată.</p>
<h4 class="gap-par">5.Verificare, modificarea conturilor si a anunturilor</h4>
<p>Verificarea/moderarea Anunțurilor publicate pe Website de către Operatorii Furnizorului are ca scop înlăturarea Anunțurilor incomplete, evident incorecte și/sau care nu respectă prevederile legale aplicabile în România sau prevederile Termenilor și Condițiilor (de exemplu, au un conținut jignitor sau calomnios, sunt contrare bunelor practici, induc în eroare Utilizatorii etc.), încercând astfel să se ofere celorlalți Utilizatori un număr cât mai mic de Anunțuri eronate.</p>
<p>Cu excepția celor prevăzute în Articolul 6 de mai sus, nu este permisă publicarea mai multor Anunțuri pentru același Produs.</p>
<p>Nu este permisă ștergerea și republicarea Anunțurilor cu același conținut.</p>
<p>Un Anunț este valabil pentru un singur Produs. Nu sunt admise spre publicare Anunțuri care fac referire la mai multe Produse.</p>
<p>Nu pot fi publicate Anunțuri false, interpretabile sau care conțin date cu caracter personal în cadrul descrierii lor.</p>
<p>Nu sunt admise spre publicare Anunțuri care contin prețuri considerate neserioase de către Furnizor (de exemplu, dar fără a se limita la, prețuri de 1 leu sau prețuri mult inferioare pieței/statisticilor aflate la dispoziția Furnizorului).</p>
<p>Nu sunt admise spre publicare Anunțuri care conțin poze preluate din alte surse (pozele care prezintă sigla altor site-uri care pot afecta imaginea Furnizorului, înscrisuri sau poze cu titlu de prezentare oferite de producători sau alte agenții media cu privire la obiectul Anunțului), cu excepția Produselor noi și sigilate. Nu sunt admise spre publicare Anunțurile care conțin poze care încalcă drepturile de proprietate intelectuală ale terților. Utilizatorii au obligația de a se asigura că Anunțurile publicate de către aceștia respectă în totalitate drepturile de proprietate intelectuala ale terților.</p>
<p>Nu sunt admise spre publicare Anunțuri pentru:</p>
<ul>
  <li>droguri, respectiv plantele și substanțele stupefiante ori psihotrope sau amestecurile care conțin asemenea plante și substanțe, astfel cum sunt definite prin Legea nr. 143/2000, precum și precursorii acestora și orice alte plante, substanțe și amestecuri cu efecte similare;</li>
  <li>materiale cu caracter obscen, respectiv obiecte, gravuri, fotografii, holograme, desene, scrieri, imprimate, embleme, publicații, filme, înregistrări video și audio, spoturi publicitare, programe și aplicații informatice, piese muzicale, precum și orice alte forme de exprimare care prezintă explicit sau sugerează o activitate sexuală;</li>
  <li>alcool și băuturi alcoolice;</li>
  <li>țigări și produse din tutun;</li>
  <li>servicii ghicitoare, clarvăzătoare, tarot și alte activități similare;</li>
  <li>bunuri care provin din săvârșirea oricărei infracțiuni, inclusiv, dar fără a se limita la bunurile obținute prin furt, tâlhărie, înșelăciune;</li>
  <li>produse contrafăcute, falsificate sau replici ale unor produse originale, precum și orice produse sau servicii care încalcă drepturile de proprietate intelectuală ale unui terț, inclusiv muzică, filme, software sau alte opere care încalca drepturile de autor sau alte drepturi de proprietate intelectuală;</li>
  <li>bunuri de natură să inducă în eroare Utilizatorii cu privire la calitățile esențiale ale acestora sau cu privire la însăși existența bunului respectiv;</li>
  <li>bunuri periculoase pentru sănătatea și viața umană, inclusiv, dar fără a se limita la biocide, pesticide extrem de periculoase, substanțe și preparate chimice periculoase;</li>
  <li>servicii matrimoniale, servicii care presupun sau sugerează activități sexuale, activități de videochat, servicii de escortă, masaj erotic sau alte servicii asemănătoare;</li>
  <li>oferte sau cereri de locuri de muncă în legătură cu sau care implică masaj erotic, participarea în filme pentru adulți, servicii care presupun sau sugerează activități sexuale, activități de videochat, servicii de escortă sau alte servicii asemănătoare;</li>
  <li>oferte de locuri de muncă tip multi-level marketing (sistemele de vânzări de tip piramidal) sau de lucru de acasă online;</li>
  <li>anunțuri privind cererea de bunuri sau servicii, cu excepția celor ce se încadrează în categoria Locuri de muncă;</li>
  <li>explozibili și articole pirotehnice (artificii, petarde), cu excepția articolelor pirotehnice de divertisment din categoria F1, în conformitate cu Hotărârea de Guvern nr. 1102/2014 privind stabilirea condițiilor pentru punerea la dispoziție pe piață a articolelor pirotehnice;</li>
  <li>arme și muniții interzise, arme și muniții letale supuse autorizării, precum și arme și muniții neletale, inclusiv arme militare, arme de vânătoare, arme de asomare, arme cu tranchilizante, arme de colecție, arme de panoplie și arme albe (baionete, săbii, spade, florete, pumnale, cuțite, sisuri, boxuri, castete, arbalete, arcuri, bâte, măciuci și bastoane telescopice), cu excepția armelor care se încadrează în categoria E - Alte categorii de arme și dispozitive neletale potrivit Legii nr. 295/2004, comercializate în condițiile legii; </li>
  <li>lucrări de diplomă, licență, disertație sau alte lucrări similare, servicii de redactare a acestora, precum și alte bunuri sau servicii având ca scop fraudarea sistemului educațional;</li>
  <li>servicii de împrumut, amanet, creditare, cămătărie sau alte activități similare;</li>
  <li>produse farmaceutice și medicamente, cu excepția suplimentelor alimentare și vitaminelor, comercializate în condițiile legii;</li>
  <li>organe umane;</li>
  <li>jocuri de noroc, tranzacții efectuate prin intermediul monedelor virtuale;</li>
  <li>servicii de deblocare iCloud;</li>
  <li>bunuri care nu se află pe teritoriul României;</li>
  <li>specii de faună și floră protejate de lege, animale pe cale de dispariție;</li>
  <li>anunțuri prin care se oferă, spre montă (împerechere)/reproducere, animale de companie;</li>
  <li>comercializarea câinilor din rasele pit bull, boerbull, bandog și metișii lor;</li>
  <li>comercializarea animalelor de companie fără obținerea și deținerea documentelor de autorizare prevăzute de lege (certificat pedigree, carnet de sănătate, alte documente de origine).</li>
  <li>comercializarea cărnii și produselor din carne de către persoanele fizice;</li>
  <li>comercializarea porcilor vii;</li>
  <li>comercializarea fildeșului (ivoriului) sau a oricărui produs care conține fildeș.</li>
  <li>prestarea serviciilor sau comercializarea produselor/echipamentelor privind modificarea sistemelor de control al emisiilor de NOx ale autovehiculelor, conform art. 14, alin. 1, lit. h) din OG nr. 78/2000 cu modificările și completările ulterioare.</li>
</ul>
<p>Anunțurile de comercializare a animalelor de companie trebuie să respecte OUG 155/2001 privind aprobarea programului de gestionare a câinilor fără stăpân, Legea 60/2004 pentru Ratificarea Convenției Europene pentru protecția animalelor de companie, OUG 55/2002 pentru regimul de deținere a câinilor periculoși sau agresivi, precum și orice restricții impuse de Autoritatea Națională Sanitară Veterinară și pentru Siguranța Alimentelor sau de autoritățile locale.</p>
<p>Nu sunt permise Anunțurile de comercializare a câinilor și pisicilor, cu excepția câinilor și pisicilor care provin de la adăposturi de animale, asociații de profil, precum și câinilor și pisicilor care provin de la crescători autorizați, cu certificare pedigree și carnet de sănătate. În cazul anunțurilor de vânzare a câinilor și/sau pisicilor, Utilizatorul se obligă să menționeze în descrierea Anunțului codul de pedigree aferent certificatului pe care îl deține pentru animalul de companie. Furnizorul își rezervă dreptul de a-i solicita Utilizatorului documente de origine și clarificări suplimentare cu privire la Anunțul postat, precum carnetul de sănătate al câinelui/pisicii oferit spre vânzare.</p>
<p>Anunțurile de comercializare a biletelor la evenimente (spectacole în aer liber, concerte, evenimente sportive, etc) pot fi retrase de pe Website, la cererea organizatorului (de ex. Untold și Neversea).</p>
<p>Nu pot fi publicate Anunțuri care conțin link-uri către alte website-uri concurente.</p>
<p>Nu este permisă manipularea cuvintelor cheie din conținutul Anunțului (introducerea în titlul sau descrierea Anunțului de cuvinte cheie care nu au legătură cu Produsul/serviciul oferit).</p>
<p>Nu pot fi publicate Anunțuri în altă limbă decât cea Română sau care conțin un limbaj necorespunzător.</p>
<p>Nu se admit Anunțuri care conțin ca date de contact numere de telefon cu suprataxă.</p>
<p>Nu sunt permise mesajele electronice nesolicitate (denumite general spam). Orice Anunț care încurajează aceste mesaje sau oferă un loc de muncă care presupune trimiterea lor va fi dezactivat.</p>
<p>Anunțurile, fie ele active pe site sau blocate la moderare, sunt verificate de către Furnizor, iar Anunțurile care nu respectă Termenii și Condițiile Website-ului vor fi șterse de pe Website, în cel mai scurt timp posibil, iar în anumite cazuri pot fi luate măsuri de blocare a contului din care s-au publicat.</p>
<p>Angrro poate verifica conformitatea Anunțurilor cu Termenii și Condițiile Website-ului, selectiv, în funcție de propriile sale criterii de prioritizare, cum ar fi, printre altele, zona geografică pentru care au fost publicate Anunțurile.</p>
<p>Ca urmare a constatării nerespectării oricăror dintre prevederile prezentului document de către oricare dintre Anunțurile publicate pe Website (inclusiv cele plătite pentru a fi promovate sau plătite deoarece depășesc numărul de Anunțuri gratuite permise în anumite categorii), Operatorii Furnizorului vor avea dreptul, în functie de situația concretă, de la caz la caz:</p>
<ul>
  <li>fie să modifice parțial Anunțul, în măsura în care acest lucru este posibil, astfel încât să se evite ștergerea Anunțului respectiv de pe Website și să se îndrepte erorile sau inadvertențele constatate;</li>
  <li>fie să se întrerupă continuitatea publicării Anunțului, prin refuzarea lui. Refuzarea Anunțului înseamnă dezactivarea postării acestuia de pe Website.</li>
</ul>
<p>În cazul refuzării Anunțului și ștergerii acestuia de pe Website, Utilizatorul va fi informat, în scris, prin e-mail, despre motivul refuzului, acesta având posibilitatea de a remedia problema și a republica Anunțul.</p>
<p>În cazul în care este refuzat la moderare un Anunț gratuit, dintr-o categorie unde există Limite de Anunțuri Gratuite stabilite de Furnizor, Anunțul respectiv este considerat ca fiind folosit, în contorizarea numărului de Anunțuri Gratuite disponibile spre publicare, timp de 30 de zile de la data publicării. Așadar, cu titlu de exemplu, dacă un Utilizator publică un Anunț Gratuit într-o categorie unde limita de Anunțuri Gratuite este 2, iar acesta este respins la moderare, Utilizatorul va putea publica gratuit un singur Anunț în aceeași categorie, în următoarele 30 de zile. Excepțiile cu privire la perioada de timp în care se pot publica Anunțuri gratuite sunt expres prevăzute aici.</p>
<p>În situația în care un Anunț plătit pentru a fi promovat sau plătit deoarece depășește numărul de Anunțuri gratuite permise în anumite categorii de pe Website este dezactivat de către Furnizor, în urma verificării, deoarece încalcă Termenii și Condițiile, Utilizatorul va primi în contul său de pe Website, credit echivalent cu prețul achitat. Acest credit va putea fi folosit doar pentru promovarea unuia sau mai multor Anunțuri sau pentru publicarea unor Anunțuri peste limita gratuită acceptată pe Website, care respectă Termenii și Condițiile și nu poate fi returnat sub formă de bani. În cazul încălcărilor grave și repetate ale prevederilor prezentului document și legilor în vigoare, Furnizorul își rezervă dreptul de a nu restitui sumele respective.</p>
<p>În cazul achiziționării de pachete de Anunțuri, respingerea la moderare a unui Anunț din pachet duce la scăderea numărului de Anunțuri disponibile din pachet. Mai exact, Anunțul nefolosit nu este re-adăugat la numărul de Anunțuri disponibile, iar sumele achitate de Utilizatori cu ocazia achiziționării pachetului de Anunțuri nu se returnează.</p>
<p>În cazul în care refuzarea la moderare a unui Anunț gratis face ca numărul total de Anunțuri rămase active să fie sub limita stabilită, nu se rambursează prețul niciunui Anunț deja plătit. Cu titlu de exemplu, dacă un Utilizator înregistrează două Anunțuri gratuite și un al treilea taxabil, acestea sunt moderate simultan, iar unul dintre Anunțurile gratuite este refuzat, în acest caz, deși limita Anunțurilor gratuite active pe Website nu este depășită, prețul celui de-al treilea Anunț nu se rambursează, deoarece momentul determinării statusului unui Anunț drept Anunț plătit sau Anunț Gratuit este momentul înregistrării efective (care este anterior moderării).</p>
<p>În cazul în care Utilizatorul publică în mod repetat Anunțul fără a remedia problemele semnalate, Furnizorul își rezervă dreptul de a bloca accesul Utilizatorului la Website în vederea postării de noi Anunțuri sau administrării Anunțurilor existente.</p>
<p>În situația modificării Termenilor și Condițiilor, modificările intervenite nu se vor aplica acordurilor privind publicarea unor Anunțuri care au fost încheiate între Furnizor și Utilizatori sub egida Termenilor și Condițiilor anteriori.</p>
<p>Numărul maxim de Anunțuri care pot fi publicate gratuit în contul unui Utilizator al Website-ului este 100.</p>
<p>În cazul în care un Anunț promovat sau plătit deoarece depășește numărul de Anunțuri gratuite permise în anumite categorii de pe Website este raportat ca fiind expirat, iar dacă din verificările echipei de moderare reiese faptul că obiectul/serviciul din Anunț nu mai este valabil, acesta va fi dezactivat, iar suma platită de Utilizator pentru acest Anunț nu se va restitui în contul Angrro.ro.</p>
<p>Furnizorul poate valida conturile Utilizatorilor Paginii Angrro folosind verificarea prin SMS, scopul fiind acela de a se asigura că fiecare cont este asociat unui Utilizator real și unic. Verificarea prin SMS presupune ca Utilizatorii să își valideze contul pe Pagina Angrro, prin intermediul unui cod trimis prin SMS, de către Furnizor, pe un număr de telefon valid aflat în posesia Utilizatorului.</p>
<p>Nu este percepută nicio taxă Utilizatorului pentru validarea contului său, întregul serviciu fiind oferit gratuit de Furnizor.</p>
<p>În cazul în care Utilizatorul nu este de acord cu validarea contului, acesta din urma va continua să fie activ pe Website, însă va avea funcționalitate limitată. Funcționalitatea limitată a unui cont presupune faptul că Utilizatorul nu mai poate publica Anunțuri noi, reactualiza, promova, prelungi sau reactiva alte Anunțuri până când contul nu este verificat prin SMS.</p>
<p>Într-un cont cu funcționalitate limitată, Utilizatorul va putea doar să raspundă la apelurile telefonice, să primească mesaje și să își dezactiveze sau șteargă permanent Anunțurile. Utilizatorul nu va putea să răspundă la mesaje, nu va putea să editeze, în niciun fel, Anunțurile deja postate și nici nu va putea să posteze Anunțuri noi.</p>
<p>În situația în care un Utilizator își validează prin SMS mai multe conturi, folosind același număr de telefon, toate conturile astfel verificate vor avea funcționalitate limitată, iar Utilizatorului i se va solicita alegerea unuia dintre ele. Contul ales de Utilizator va reveni la funcționalitate totală, iar restul conturilor vor rămâne limitate.</p>
<p>Un Utilizator poate solicita maxim 5 SMS-uri cu coduri de verificare, în decurs de 24 de ore.</p>
<p>Validarea contului se face o singură dată pentru fiecare cont, până când acesta este verificat cu succes prin SMS de către Utilizator.</p>
<p>Odată validat, contul Utilizatorului va rămâne asociat cu numărul de telefon folosit la verificarea prin SMS. Dacă Utilizatorul dorește schimbarea numărului de telefon asociat contului Angrro, acesta va trebui să contacteze echipa de Suport Clienți, trimițând un email la adresa contact@angrro.ro.</p>
<p>Dacă nu există activitate în contul Utilizatorului timp de 24 de luni, Furnizorul își rezervă dreptul de a șterge respectivul cont, inclusiv toate datele personale stocate în cont, ceea ce înseamnă că Utilizatorul nu îl mai poate accesa și utiliza. Cu toate acestea, Furnizorul nu va șterge contul în cazul în care acesta conține tranzacții deschise sau Utilizatorul are dreptul la o rambursare a creditului de la Furnizor. Înainte de a șterge contul, Furnizorul va contacta Utilizatorul pentru a confirma că nu mai dorește să continue utilizarea contului.</p>
<h4 class="gap-par">6. Procedura de depunere și soluționare a plângerilor și sesizărilor primite din partea Utilizatorilor </h4>
<p>Orice Utilizator poate depune o plângere sau sesizare care privește sau are legătură cu serviciile oferite de Furnizor, respectiv Anunțurile transmise/publicate/nepublicate de Angrro pe Website, în termen de maxim 7 zile de la data producerii evenimentului și/sau apariției cazului sesizat.</p>
<p>Utilizatorii au posibilitatea să transmită Furnizorului oricând plângeri și/sau sesizări cu privire la activitățile cu aparență nelegală desfășurate de un Utilizator al Website-ului care privesc și/sau au legătura cu serviciile furnizate de Angro, ori cu privire la informațiile cu aparență nelegală furnizate de un Utilizator al Website-ului, despre care au cunoștință.</p>
<p>Plângerile vor fi depuse prin intermediul formularului de contact aflat pe Website, pe care îl puteți accesa și de aici.</p>
<p>Plângerile și/sau sesizările transmise Furnizorului vor include datele de identificare a Utilizatorului, numărul de identificare a Anunțului ce face obiectul plângerii (dacă reclamația sau sesizarea priveste un anumit Anunț), precum și orice alte date necesare Furnizorului în vederea identificării evenimentului sesizat și/sau a Anunțului reclamat (după caz) și o descriere cât mai detaliată a motivului pentru care a fost înaintată plângerea/sesizarea, astfel încat Furnizorul să o poată soluționa în cel mai scurt timp posibil.</p>
<p>Plângerile/sesizările vor fi analizate și vor primi răspuns în termen de maxim 30 de zile lucrătoare de la primirea acestora de către Furnizor, în cazul în care au fost însoțite de un set complet de date necesare identificării Utilizatorului, Anunțului și/sau a problemei. În situația în care petentul nu a transmis Furnizorului toate datele necesare identificării problemelor semnalate și soluționării plângerii/sesizării respective, acesta va fi înștiințat de Furnizor cu privire la informațiile lipsă, urmând ca termenul de soluționare de mai sus să fie prelungit corespunzător.</p>
<p>Pentru a se adresa Autorității Naționale pentru Protecția Consumatorilor, Utilizatorul poate accesa link-ul: http://www.anpc.gov.ro</p>
<h4 class="gap-par">7.   Acordul cu privire la prelucrarea și colectarea Datelor cu Caracter Personal </h4>
<p>Angrro prelucrează datele personale ale Utilizatorilor săi în concordanță cu Politica de confidențialitate.</p>
<h4 class="gap-par">8. Modificările Termenilor și Condițiilor Website-ului</h4>
<p>Furnizorul își rezervă dreptul de a modifica Termenii și Condițiile. Puteți accesa Termenii și Condițiile oricând la adresa: angrro.ro/termeni-de-utilizare</p>
<p>Dacă nu sunteți de acord cu modificările realizate, opțiunea pe care o aveți la dispoziție este să ștergeți contul înregistrat pe Website sau să nu mai accesați, să vizitați sau să utilizați, în orice mod, Website-ul. </p>
<h4 class="gap-par">9.  Legea aplicabilă. Litigii</h4>
<p>Drepturile și obligațiile părților, menționate în acești Termeni și Condiții, precum și toate efectele juridice pe care prezentul document le produce sunt guvernate de legea română în vigoare.</p>
<p>Orice litigiu care are ca obiect o dispută în legătură cu acești Termeni și Condiții va fi soluționat de instanțele competente din România.</p>
</div>
